# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'warehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\"|\n\x0bProductData\x12\x11\n\tproductID\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x17\n\x0fproductCategory\x18\x03 \x01(\t\x12\x13\n\x0bproductUnit\x18\x04 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x05 \x01(\x05\"\xd2\x01\n\tWarehouse\x12\x13\n\x0bwarehouseID\x18\x01 \x01(\t\x12\x15\n\rwarehouseName\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x18\n\x10warehouseAddress\x18\x04 \x01(\t\x12\x1b\n\x13warehousePostalCode\x18\x05 \x01(\t\x12\x15\n\rwarehouseCity\x18\x06 \x01(\t\x12\x18\n\x10warehouseCountry\x18\x07 \x01(\t\x12\x1e\n\x08products\x18\x08 \x03(\x0b\x32\x0c.ProductData\",\n\x10WarehouseRequest\x12\x18\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\n.Warehouse\"$\n\x11WarehouseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2N\n\x10WarehouseService\x12:\n\x11SendWarehouseData\x12\x11.WarehouseRequest\x1a\x12.WarehouseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTDATA']._serialized_start=19
  _globals['_PRODUCTDATA']._serialized_end=143
  _globals['_WAREHOUSE']._serialized_start=146
  _globals['_WAREHOUSE']._serialized_end=356
  _globals['_WAREHOUSEREQUEST']._serialized_start=358
  _globals['_WAREHOUSEREQUEST']._serialized_end=402
  _globals['_WAREHOUSERESPONSE']._serialized_start=404
  _globals['_WAREHOUSERESPONSE']._serialized_end=440
  _globals['_WAREHOUSESERVICE']._serialized_start=442
  _globals['_WAREHOUSESERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
